### ISSUE TITLE
Invalid conjur version number

### ISSUE THREAD

**Issue by AndrewCopeland** [cyberark/kubernetes-conjur-deploy#113]
We should validate Conjur version is 4 or 5 rather than looking at the arbitrary image name to validate version. Currently this section is failing because our image name is cyberark/dap:11.2.1.

https://github.com/cyberark/kubernetes-conjur-deploy/blob/045f3c2496585f0dee4044876225d031f288cb36/0_check_dependencies.sh#L22-L28

**Comment by izgeri** [comment]
Note - we could probably update this to check that if the image tag is 4.x, that the CONJUR_VERSION is 4, and that it's 5 otherwise

**Comment by izgeri** [comment]
@andrewcopeland thanks for flagging this - we've updated the project to support the v5 API by default now, so that `CONJUR_VERSION` defaults to 5, and we've moved v4 support to a branch and removed it from the main project.
