### ISSUE TITLE
Align deploy-oss branch with master

### ISSUE THREAD

**Issue by eladkug** [cyberark/kubernetes-conjur-deploy#118]
cyberark--kubernetes-conjur-deploy job is running as part of cyberark--secrets-provider-for-k8s, but today we are working with different branch(deploy-oss) for it and not with master.
Need to understand if we want to run it for oss as well (today ran for DAP only)
Implement helm chart will take a while so for now we want to align deploy repo for master since we saw it can give us a great value.
We will take helm chart as a different task, already raised a question on slack for this.
DOD:

- [ ]  Working with conjur-deploy master working as today + running on oss environment as well
- [x]  Verify secrert-provider-for-k8s working
- [ ]  Verify no change in documentation
- [ ]  The default behavior is running DAP tests

**Comment by izgeri** [comment]
As noted elsewhere:
> Rather than adding an OSS flow to the master branch of k8s-deploy (a repo which we give to DAP customers), can you migrate the secrets provider repo to use the helm chart and close the k8s-deploy branch?
>
> We use the helm chart in the [OSS suite gh action](https://github.com/cyberark/conjur-oss-suite-release/blob/master/.github/workflows/e2e-tests.yml) to test Conjur OSS against Secretless - perhaps the tests there provide a model you could follow? I have concerns about polluting the experience in k8s-deploy (which is already not great) with OSS flows, when up to now it's been purely DAP. Additionally, OSS deployment in k8s is not as complex as DAP follower deployment because of the helm chart, and that is the correct technical tool to leverage for deploying OSS to k8s.

**Comment by eladkug** [comment]
@izgeri i took your advise and we will continue to work with different branch. 
A new ticket [119](https://app.zenhub.com/workspaces/palmtree-5d99d900491c060001c85cba/issues/cyberark/kubernetes-conjur-deploy/119) for helm chart migration. 

Anyway for now we align our current branch with master, so our branch is updated, I verified 
secrets-provider-for-k8s is working with our updated branch.
