### ISSUE TITLE
CLI container doesn't work and returns 502 bad gateway

### ISSUE THREAD

**Issue by izgeri** [cyberark/kubernetes-conjur-deploy#76]
If you try to use the CLI container that is deployed with these scripts, you get an error like
```
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
error: 502 Bad Gateway
```

I have seen this with DAP clusters deployed both in and outside openshift 3.9.

**Comment by sgnn7** [comment]
Closed by parent issue https://github.com/cyberark/kubernetes-conjur-deploy/issues/80
